Feature: content for the landing page
bearmetaldev/main-website pull request #3
Opened 2024-07-01 22:58 UTC by odesenfans

Problem: we want actual content.

Solution: add a description for each section that describes our activities.

2024-07-02 12:31 UTC, nourgm10 requested changes

2024-07-02 12:31 UTC, nourgm10 commented on frontend/app/components/web3/web3-content.tsx
How about "our experience and technical prowess will guide your project towards success" instead of "to success"?

2024-07-02 12:31 UTC, nourgm10 commented on frontend/app/components/engineering/engineering-content.tsx
Here I would change "our engineering prowess extends to a wide array" to "our engineering skills encompass a wide aray", as we just used "our experience and technical prowess" in the Web3 section above.

2024-07-02 12:31 UTC, nourgm10 commented on frontend/app/components/engineering/engineering-content.tsx
I would also replace "Let us help you turn your most ambitious engineering challenges into reality" with "Let us help you bring your most ambitious engineering challenges to reality"

2024-07-02 12:31 UTC, nourgm10 commented on frontend/app/components/trainings/trainings-content.tsx
Should we remove this section for now?

2024-07-02 22:57 UTC, odesenfans commented on frontend/app/components/trainings/trainings-content.tsx
It's fine, we can leave it even if it's pretty basic.

2024-07-03 08:15 UTC, nourgm10 approved these changes

2024-07-03 08:15 UTC, nourgm10 approved these changes

2024-07-03 08:17 UTC, nourgm10 commented on frontend/app/components/web3/web3-content.tsx
It seems like this review is missing for me to approve all the changes

2024-07-03 08:29 UTC, merged